# Generated by Django 2.2 on 2020-01-28 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_auto_20200124_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 28)),
        ),
    ]
