# Generated by Django 2.2 on 2020-02-01 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20200131_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 1)),
        ),
    ]
