# Generated by Django 2.2 on 2020-02-02 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20200201_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 2)),
        ),
    ]
