# Generated by Django 2.2 on 2020-01-31 02:24

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.image_path)),
            ],
        ),
    ]
