# Generated by Django 2.2 on 2020-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treehole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=20)),
                ('answer', models.TextField(max_length=20)),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['create_time']},
        ),
    ]
