# Generated by Django 2.2 on 2020-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treehole', '0002_auto_20200201_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
