# Generated by Django 2.2 on 2020-02-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treehole', '0003_saying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saying',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
